### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dmaretskyi** [EthWorks/hostlify#1]
## Stage 1. Configure Nginx

- [x] Figure out how to test domains locally `*.lvh.me`
- [x] Serve 2 separate builds under different domains: `build1.hostlify.local`, `build2.hostlify.local`

## Stage 2. API server

- [x] Create node api server with typescript, express (or something else?)
- [x] Make nginx forward api requests from root domain `lvh.me` to the API
- [x] Make api generate config
- [x] List all subdirectories in the `repository` directory
  - [x] For each generate an nginx conf file that serves it under a proper subdomain
  - [x] Include generated configs from the main config file
  - [x] Add default404 nginx
- [x] Add `/upload/:id` route that uploads a new build to the repository
  - [x] Place files in the proper direcotry
  - [x] Regenerate config
  - [x] Run command to reload nginx config `nginx -s reload` or `docker exec <container id> nginx -s reload`
  - [x] Docker compose exec...
  - [x] Return `OK 201 Created` `{ "url": "build123.lvh.me" }`

## Stage 3. Docker build

- [x] Build single docker image with nginx and node api server
